server:
  port: 8005

spring:
  application:
    name: cloud-nacos-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/tsj-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tsj.springcloud.entities  # 所有Entity别名类所在包

management:
  endpoints:
    web:
      exposure:
        include: '*'