server:
  port: 8009

spring:
  application:
    name: cloud-seata-8009
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    alibaba:
      seata:
        tx-service-group: tsj-tx-group
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tsj.springcloud.entities,com.tsj.springcloud.entity  # 所有Entity别名类所在包
